### ISSUE TITLE
pip install failed, can it work in py3?

### ISSUE THREAD

**Issue by ChanceAroundYou** [DelightRun/PyBaiduYuyin#9]
pip install failed, can it work in  #py3.5?

> Collecting PyBaiduyuyin
  Using cached PyBaiduYuyin-0.1.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Cheer.L\AppData\Local\Temp\pip-build-ik3qss4a\PyBaiduyuyin\setup.py", line 11, in <module>
        import PyBaiduYuyin
      File "c:\users\cheer.l\appdata\local\temp\pip-build-ik3qss4a\pybaiduyuyin\PyBaiduYuyin\__init__.py", line 492
        print 'You said ' + text
                        ^
    SyntaxError: Missing parentheses in call to 'print'

**Comment by ChanceAroundYou** [comment]
[https://github.com/DelightRun/PyBaiduYuyin/blob/master/PyBaiduYuyin/__init__.py#L492](url)
i've found that, in PyBaiduYuyin.__init__.py line492
>  while True:
        print("Say something!")
        with m as source:
            audio = r.listen(source)
        print("Got it! Now to recognize it...")
        try:
            text = r.recognize(audio)
            **print 'You said ' + text**
        except LookupError:
            print("Oops! Didn't catch that")

this print is differnt from others, which is py2 style.

**Comment by ideas4u** [comment]
thanks,CheerL .I changed the print to print();and then it works.
